// <auto-generated />
using System;
using CP2_DotNet.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CP2_DotNet.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP2_DotNet.API.Models.AvaliacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("a_autor");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("a_comentario");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("a_dataavaliacao");

                    b.Property<int>("FilmeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("f_id");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("a_nota");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.ToTable("tb_avaliacao");
                });

            modelBuilder.Entity("CP2_DotNet.API.Models.FilmeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("f_anolancamento");

                    b.Property<int>("DuracaoMin")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("f_duracao");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("f_genero");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("f_titulo");

                    b.HasKey("Id");

                    b.ToTable("tb_filme");
                });

            modelBuilder.Entity("CP2_DotNet.API.Models.AvaliacaoEntity", b =>
                {
                    b.HasOne("CP2_DotNet.API.Models.FilmeEntity", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");
                });
#pragma warning restore 612, 618
        }
    }
}
